name: build-pack

on:
  push:
    branches:
    - main
  schedule:
    - cron: "5 5 * * *"
    - cron: "5 13 * * *"
    - cron: "5 22 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Emacs
      run: sudo apt install --no-install-recommends emacs
    - name: Run rssingl.el
      run: emacs -Q --script rssingle.el
    - name: Upload updates database
      run: |
        rm -rf elfeed-db
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git add elfeed-db
        git commit --allow-empty -m "$(date +"%F")_database"
        git push -f origin main
    - name: Upload new index.xml
      run: |
        rm -rf docs/index.xml
        mv index.xml docs
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git add docs/index.xml
        git commit --allow-empty -m "$(date +"%F")_index"
        git push -f origin main
